SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[CUSTOM_KLIENTI] (
		[ID_KLIENTI_KLNT]     [int] NOT NULL,
		[NREG]                [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[NCER]                [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[SCER]                [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[DCER]                [smalldatetime] NULL,
		[LEGP]                [bit] NULL,
		[DHPO]                [bit] NULL,
		[TRAZ]                [bit] NULL,
		[POBA]                [bit] NULL,
		[REZI]                [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[RREG]                [varchar](200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[RSEK]                [varchar](200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[CRBB]                [bit] NULL,
		[CRBP]                [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[PGEM]                [bit] NULL,
		[CSEC]                [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[FINL]                [bit] NULL,
		[HOLN]                [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[FRSC]                [int] NULL,
		[EMPS]                [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[PLSV]                [char](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[REZV]                [numeric](15, 2) NULL,
		[REVA]                [char](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[DEZV]                [numeric](15, 2) NULL,
		[DEVA]                [char](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[AIZV]                [numeric](15, 2) NULL,
		[AIVA]                [char](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[NIZV]                [numeric](15, 2) NULL,
		[NIVA]                [char](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[CPZV]                [numeric](15, 2) NULL,
		[CPVA]                [char](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[FAZV]                [numeric](15, 2) NULL,
		[FAVA]                [char](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[IAZV]                [numeric](15, 2) NULL,
		[IAVA]                [char](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[OCVA]                [char](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[OLZE]                [numeric](15, 2) NULL,
		[OLZC]                [numeric](15, 2) NULL,
		[OLZR]                [numeric](15, 2) NULL,
		[CCZE]                [numeric](15, 2) NULL,
		[CCZC]                [numeric](15, 2) NULL,
		[CCZR]                [numeric](15, 2) NULL,
		[PAYB]                [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[CRLT]                [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[INSH]                [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[PFGP]                [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[CIPE]                [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[CRBX]                [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[OWNC]                [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[BRAA]                [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[COME]                [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[CLCO]                [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[SUCO]                [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[PRCO]                [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[COMP]                [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[MANE]                [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[ID_S106_RCSC]        [int] NULL,
		[ID_S106_RRCS]        [int] NULL,
		[ID_S106_RLOG]        [int] NULL,
		[ID_S106_RBRO]        [int] NULL,
		[ID_S106_RASM]        [int] NULL,
		[NBLV]                [bit] NULL,
		[BNUM]                [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[BENT]                [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[APTN]                [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[ALCO]                [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[FREA]                [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[BNUP]                [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[BENP]                [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[APTP]                [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[FREP]                [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[CSAT]                [bit] NULL,
		[CLSD]                [smalldatetime] NULL,
		[TACT]                [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[BLCO]                [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[PUPO]                [varchar](200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[VIPX]                [bit] NULL,
		[GUDP]                [bit] NULL,
		[XCRP]                [bit] NULL,
		[SRWB]                [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[ORFU]                [varchar](200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[JUPR]                [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[URRU]                [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[UNEM]                [bit] NULL,
		[DUNE]                [smalldatetime] NULL,
		[DEBR]                [numeric](9, 6) NULL,
		[BGIC]                [bit] NULL,
		[BGPE]                [bit] NULL,
		[BGSR]                [bit] NULL,
		[BGPO]                [bit] NULL,
		[INPT]                [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[DINP]                [smalldatetime] NULL,
		[AUTH]                [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[DAUT]                [smalldatetime] NULL,
		[MPFU]                [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[MPFH]                [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[MEFA]                [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[PERF]                [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[SDMA]                [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[CPMA]                [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[CLSC]                [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[TYRC]                [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[SBAS]                [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[BASD]                [smalldatetime] NULL,
		[TOAS]                [numeric](18, 2) NULL,
		[TURN]                [numeric](18, 2) NULL,
		[IMMX]                [bit] NULL,
		[PGCU]                [bit] NULL,
		[SUC1]                [numeric](18, 2) NULL,
		[PAI1]                [numeric](18, 2) NULL,
		[CUR1]                [char](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[SUC2]                [numeric](18, 2) NULL,
		[PAI2]                [numeric](18, 2) NULL,
		[CUR2]                [char](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[SUC3]                [numeric](18, 2) NULL,
		[PAI3]                [numeric](18, 2) NULL,
		[CUR3]                [char](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[SUC4]                [numeric](18, 2) NULL,
		[PAI4]                [numeric](18, 2) NULL,
		[CUR4]                [char](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[SUC5]                [numeric](18, 2) NULL,
		[PAI5]                [numeric](18, 2) NULL,
		[CUR5]                [char](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[HIST]                [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[HISP]                [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[CJSI]                [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[POAF]                [bit] NULL,
		[MMID]                [int] NULL,
		[ID_CP_S554_KRAJ]     [int] NULL,
		[STCI]                [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[STET]                [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[STEX]				  [bit] NULL,
		[SSMS]				  [bit] NULL,
		[SSMN]				  [varchar](max) NULL,
		[ESGR]                [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[ID_SYNC]             [int] NULL,
		[ISFF]				  [bit] NULL,
		[IMAA]				  [bit] NULL,
		[DRA2]				  [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[REI2]				  [nvarchar](200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[KRJ2]				  [nvarchar](200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[SET2]				  [nvarchar](200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[UTI2]				  [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[ULC2]				  [nvarchar](200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[HIT2]				  [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[POT2]				  [nvarchar](200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[BNM2]				  [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[BET2]				  [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[APN2]				  [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[FRA2]				  [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[NAP2]				  [nvarchar](200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[DRP2]				  [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[REP2]				  [nvarchar](200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[KRP2]				  [nvarchar](200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[SEP2]				  [nvarchar](200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[UTP2]				  [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[ULP2]				  [nvarchar](200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[HIP2]				  [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[POP2]				  [nvarchar](200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[BNP2]				  [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[BEP2]				  [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[APP2]				  [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[FRP2]				  [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[CUSTOM_KLIENTI]
	ADD
	CONSTRAINT [PK_CUSTOM_KLIENTI]
	PRIMARY KEY
	CLUSTERED
	([ID_KLIENTI_KLNT])
	WITH FILLFACTOR=90
	ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_CUSTOM_KLIENTI_SYNC] ON [dbo].[CUSTOM_KLIENTI] ([ID_SYNC]) INCLUDE([ID_KLIENTI_KLNT])
GO
ALTER TABLE [dbo].[CUSTOM_KLIENTI] SET (LOCK_ESCALATION = TABLE)
GO
